# Generated by Django 2.1.7 on 2019-02-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
